Repository terraform-providers/terraform-provider-ksyun, pull requests merged in 2020-06, with the labels that each got.

#4 modify instance test
  ksyun/resource_ksyun_instance_test.go
Labels: size/XS

#6 fix eip crash and instance example
  example/instance/main.tf
  example/instanceService/main.tf
  ksyun/resource_ksyun_eip.go
  ksyun/resource_ksyun_instance_test.go
Labels: size/XS

#7 modify CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#9 show eip support & update eip
  ksyun/data_source_ksyun_krds.go
  ksyun/data_source_ksyun_krds_security_group.go
  ksyun/data_source_ksyun_sqlserver.go
  ksyun/resource_ksyun_krds.go
  ksyun/resource_ksyun_krds_read_replica.go
  ksyun/resource_ksyun_sqlserver.go
  website/docs/d/krds.html.markdown
  website/docs/d/sqlservers.html.markdown
  website/docs/r/krds.html.markdown
Labels: bug, enhancement, size/XL

#10 remove redis parameters's Computed field
  ksyun/resource_ksyun_redis_instance.go
Labels: size/S

#11 instance support update instance_type and update update instance_password
  CHANGELOG.md
  ksyun/resource_ksyun_instance.go
Labels: bug, enhancement, size/L

#12 instance update instance type add final state judge and start
  ksyun/resource_ksyun_instance.go
Labels: bug, size/S

#13 modify log
  CHANGELOG.md
Labels: documentation, size/XS
