Repository terraform-providers/terraform-provider-ksyun, pull requests merged in 2020-11, with the labels that each got.

#26 instance,eip and lb support project
  CHANGELOG.md
  ksyun/resource_ksyun_eip.go
  ksyun/resource_ksyun_eip_association.go
  ksyun/resource_ksyun_eip_association_test.go
  ksyun/resource_ksyun_eip_test.go
  ksyun/resource_ksyun_instance.go
  ksyun/resource_ksyun_instance_test.go
  ksyun/resource_ksyun_lb.go
  ksyun/resource_ksyun_lb_test.go
Labels: bug, size/M

#27 add eip for krds
  CHANGELOG.md
  example/dataRds/main.tf
  example/rds/main.tf
  ksyun/resource_ksyun_krds.go
  ksyun/resource_ksyun_krds_test.go
  website/docs/r/krds.html.markdown
Labels: bug, enhancement, size/L

#28 using fixed schema to save db instance instead of all the data in res…
  CHANGELOG.md
  ksyun/common_ksyun.go
  ksyun/common_ksyun_test.go
  ksyun/data_source_ksyun_krds.go
  ksyun/data_source_ksyun_krds_security_group.go
  ksyun/data_source_ksyun_sqlserver.go
  ksyun/resource_ksyun_krds.go
  ksyun/resource_ksyun_krds_read_replica.go
  ksyun/resource_ksyun_krds_security_group.go
  ksyun/resource_ksyun_sqlserver.go
Labels: bug, size/L

#29 fix bugs of using error az param when changing password for or renami…
  CHANGELOG.md
  ksyun/data_source_ksyun_krds.go
  ksyun/resource_ksyun_redis_instance.go
  ksyun/resource_ksyun_redis_instance_test.go
Labels: size/M
