Repository terraform-providers/terraform-provider-ksyun, pull requests merged in 2020-10, with the labels that each got.

#22 instance remove the function of creating data_disk and support show data_disk
  CHANGELOG.md
  example/instance/main.tf
  example/instanceService/main.tf
  ksyun/data_resourece_ksyun_keys.go
  ksyun/data_source_ksyun_instances.go
  ksyun/resource_ksyun_instance.go
  website/docs/r/instance.html.markdown
Labels: bug, documentation, size/M

#23 READEME.md add instructions for adding documents and links
  README.md
Labels: documentation, size/XS

#25 add security group and remove redis security rule of instance
  CHANGELOG.md
  example/dataRedisSecGroup/main.tf
  example/redis/main.tf
  go.mod
  go.sum
  ksyun/data_resourece_ksyun_keys.go
  ksyun/data_source_ksyun_redis.go
  ksyun/data_source_ksyun_redis_security_group.go
  ksyun/data_source_ksyun_redis_security_group_test.go
  ksyun/provider.go
  ksyun/resource_ksyun_redis_instance.go
  ksyun/resource_ksyun_redis_instance_test.go
  ksyun/resource_ksyun_redis_node_test.go
  ksyun/resource_ksyun_redis_security.go
  ksyun/resource_ksyun_redis_security_group.go
  ksyun/resource_ksyun_redis_security_group_allocate.go
  ksyun/resource_ksyun_redis_security_group_allocate_test.go
  ksyun/resource_ksyun_redis_security_group_rule.go
  ksyun/resource_ksyun_redis_security_group_rule_test.go
  ksyun/resource_ksyun_redis_security_group_test.go
  ksyun/resource_ksyun_redis_security_test.go
  vendor/github.com/KscSDK/ksc-sdk-go/service/kcsv1/api.go
  vendor/github.com/KscSDK/ksc-sdk-go/service/vpc/api.go
  vendor/modules.txt
  website/docs/d/ksyun_redis_security_groups.html.markdown
  website/docs/pronamespace
  website/docs/r/redis_instance.html.markdown
  website/docs/r/redis_sec_group.html.markdown
  website/docs/r/redis_sec_rule.html.markdown
  website/ksyun.erb
Labels: dependencies, documentation, new-data-source, new-resource, size/XXL
